### PR TITLE
Vector add using Jinja template

### PR DESCRIPTION
**Pull request by isazi**
Contributing an example of using kernel_tuner with a CUDA code generator that is based on the Jinja template engine. The code has few tunable parameters and has been tested on a NVIDIA Titan X Pascal on the DAS.

### CODE REVIEW

**Comment by benvanwerkhoven** [comment]
Hi Alessio,

Thanks for the example! I tried running it, but I'm getting the error: 
```
[stderr:
kernel.cu:11:25: fatal error: helper_math.h: No such file or directory
 #include <helper_math.h>
                         ^
compilation terminated.
]

$ gcc --version
gcc (GCC) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Oct_12_20:09:46_PDT_2020
Cuda compilation tools, release 11.1, V11.1.105
Build cuda_11.1.TC455_06.29190527_0
```

I did some searching it seems helper_math used to be part of the CUDA SDK but no longer is. Perhaps I get the error because I'm using CUDA 11. What do you think? Could you we do without helper_math.h?

**Comment by isazi** [comment]
I will check, maybe something changed indeed with CUDA 11. Before that was necessary to use the vectors in CUDA.

**Comment by isazi** [comment]
Found out that helper_math.h is not part of standard CUDA, so rewrote the code to work without it. Tested on the A100 with CUDA 11, it works.

**Comment by benvanwerkhoven** [comment]
Perfect! Thanks!

**Pull request merged**
