### PR TITLE
change way to get compute capability that should work also

### PR DESCRIPTION
**Pull request by ipelupessy**
if keyword not present

compute_capability is documented pycuda feature, so should be safe

### CODE REVIEW

**Comment by ipelupessy** [comment]
ok, maybe this is not a good idea
( the arch compute_ it generates here does not work..)

**Comment by ipelupessy** [comment]
the test fail is just an issue with the mock tests (needs additional workl), not related to the local fail I had

**Comment by benvanwerkhoven** [comment]
Hi Inti, is this working on your machine now? If so we should change a few things to make the code compatible with mocks.

**Comment by ipelupessy** [comment]
no, its not working here (ie the function call returns a sensible value, but these then fail when setting arch and code)

**Pull request merged**
