### PR TITLE
WIP: use correct maximum work group size for OpenCL kernels

### PR DESCRIPTION
**Pull request by egpbos**
On macOS (Sierra / 10.12 in my case, but I guess it's more general) the maximum work group size of an OpenCL kernel depends not just on the hardware, but on the compiled kernel as well. The initial commit below shows how to get this information from the compiled `pyopencl.Kernel` object, i.e.:

```py
print(func.get_work_group_info(cl.kernel_work_group_info.WORK_GROUP_SIZE, cl.get_platforms()[0].get_devices()[0]))
```

where `func` is the `Kernel` object.

For instance, on my laptop (Using: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz) this tells us the following maximum work group sizes for some of the examples:
- `vector_add.py`: 128
- `convolution.py`: 1
- `convolution_correct.py`: 128
- `matmul.py`: 1
- `reduction.py`: 1
- `sepconv.py`: 1
- `stencil.py`: 128
- `vector_add_codegen.py`: 128

The `vector_add.py` example is indeed how we found this bug, since this crashed above 128.

## Fix

Before the kernel is compiled, there should be a check on this size. However, it can only be obtained from a compiled kernel...

One possible way around this is perhaps to first compile the kernel for a work group size of 1 and get the information from that. This could be (de)activated with a flag or, alternatively, it could be run only after compilation fails in a `try-except`.

Thoughts, suggestions?

### CODE REVIEW

**Comment by benvanwerkhoven** [comment]
Hi Patrick, a workgroup size of 1 for these kernels does not make any sense. Have you tried running the kernels with sizes larger than these numbers?

**Comment by egpbos** [comment]
For completeness, this is what I get when running `vector_add.py` (similar for the other tests):

```bash
$ python vector_add.py
Using: Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
block_size_x=128, time=7.9663522
Error while benchmarking: vector_add_192
Error while compiling or benchmarking, see source files: /Users/pbos/sw/src/git/kernel_tuner/examples/opencl/temp_02idhtc6.c
Traceback (most recent call last):
 -- STUFF --
pyopencl.cffi_cl.LogicError: clEnqueueNDRangeKernel failed: INVALID_WORK_GROUP_SIZE
```

**Comment by egpbos** [comment]
@benvanwerkhoven: as far as I understand, these numbers are *maximum* work group sizes. I run the tests as they are, so the work group sizes that are requested are just those from the test scripts.

**Comment by egpbos** [comment]
Btw, I got the idea for using `func.get_work_group_info` from https://lists.tiker.net/pipermail/pyopencl/2010-April/000309.html

**Comment by egpbos** [comment]
And here is another person with the same problem (but no general solution in this case): http://pyopencl.tiker.narkive.com/ejM5UnCG/benchmark-py-os-x-cannot-do-256-workers-on-cpu

**Comment by egpbos** [comment]
Note that the pyopencl wiki is outdated on this issue (I assume he doesn't test on macOS either): https://wiki.tiker.net/OpenCLOddities
As noted in the narkive thread above, the 1 work item limit has now been partially lifted, depending on kernel.

**Comment by benvanwerkhoven** [comment]
I think that the real problem is that you are running OpenCL code intended for GPUs on your CPU. We will have a look at it tomorrow.

**Pull request merged**
